### ISSUE TITLE
Contribution request !

### ISSUE THREAD

**Issue by n53337** [Tahaa0/groundzero-front#1]
hey @Tahaa0, is everything good!
i wanna give some help on this project, which feature/s are you guys working right now ?
here's ma discord if y'all interested : `0xffff_`
Good luck !

**Comment by Tahaa0** [comment]
Hello Youssef, I am Taha from the project GroundZero, I have received your email. Thanks for your interest in contributing to the project. Would like to discuss it further with you, I have sent you a message on discord
